version: '2.4' # The highest supported version on balena IOT
volumes:
  volume_byodr_sessions:
services:
  yolo-export:
    cpuset: '0'
    build:
      context: .
      dockerfile: following_utils/Dockerfile
    restart: always
    privileged: true
    network_mode: host
    stop_signal: SIGKILL
    environment:
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra:$LD_LIBRARY_PATH
    volumes:
      - volume_byodr_sessions:/home/ftpuser:rw
  ftpd:
    cpuset: '0'
    build:
      context: .
      dockerfile: ftpd/Dockerfile
    restart: always
    command: ['python3', 'wrap.py']
    stop_signal: SIGKILL
    ports:
      - '21:21'
      - '30000-30009:30000-30009'
    volumes:
      - volume_byodr_sessions:/home/ftpuser:rw
